### ISSUE TITLE
typing spams history with entries

### ISSUE THREAD

**Issue by fuzetsu** [porsager/flems.io#12]
I just noticed today that every URL change adds an entry to the browser's history, and obviously the URL changes constantly as you type.

Resulting in this:
![image](https://user-images.githubusercontent.com/848652/42354548-9f605d34-8095-11e8-83e2-ba3bc73e96bf.png)

Is it intentional?

**Comment by fuzetsu** [comment]
Moved from https://github.com/porsager/flems/issues/56

**Comment by porsager** [comment]
Thanks for bringing this up.. I thought it was only safari doing this, but that's chrome there right? `flems.io` uses `replaceState` which shouldn't create a new entry when called, but I'll try to look into it again.

**Comment by fuzetsu** [comment]
Yes, it's chrome, I should have said. That's odd though...

**Comment by porsager** [comment]
Apparently chrome[1], firefox[2] and safari[3] thinks they should add an entry to the global history when using `history.replaceState` which seems very wrong to me since the very purpose or having `replaceState` and `pushState` is to differ in this behavior. Unfortunately I don't think it's something that'll change any time soon, but I found that chrome at least won't add to global history if I use `location.hash = ...` instead, so I've changed to that now (safari and firefox are still misbehaving).

I'll close this for now as I don't think there's more I can do :-(

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=917784 (could not find an existing issue, so had to file one myself)
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=753264 (seems stalled)
[3] https://bugs.webkit.org/show_bug.cgi?id=142151 (they blamed safari so bugs are hidden in apples bugreporter)
