### ISSUE TITLE
Save to a gist

### ISSUE THREAD

**Issue by tivac** [porsager/flems.io#14]
I love using flems.io to prototype ideas, and while I can save the URL into a local document to keep track of milestones I'd love to instead be able to press a button and save it out to a gist. The [svelte REPL](https://svelte.technology/repl?demo=hello-world) does this and it's great to be able to go back through the gist history and see how the idea morphed over time.

Obviously I could do this with a real git repo, but the whole point of what I love about flems.io is how fast it is to get started trying out ideas!

**Comment by porsager** [comment]
Hi @tivac .. Sorry for the late response!!

You're absolutely right!

I've got most of the code ready for it since I first implemented the upcoming persisted flems feature using gists. Unfortunately it didn't have the speed I had hoped, and there were a few things missing to make the features I wanted.

Even so I still want to include the option of saving to and loading from gists, so once I find the time to finish up persistence it will be added at the same time.

The only thing missing is UI polishing and some error handling, so hopefully it shouldn't be long..

**Comment by porsager** [comment]
Wow.. how time passes by. 

I might retrofit the code from persistent flems to do this before persistent flems is done, so yeah, one day hopefully..

**Comment by leothelocust** [comment]
Any update here @porsager? I am really digging this project btw, just found it!

**Comment by porsager** [comment]
I would have loved to come around to this, but I'm gonna close the issue to focus on other things so I might one day have time for this.
